id: P000154
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཕུང་ཁམས་སྐྱེ་མཆེད་ཀྱི་རྣམ་གཞག་ཇི་སྙེད་ཤེས་བྱའི་སྒོ་འབྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors: []
  layers:
  - book_title
  - quotation
  - yigchung
  id: IBA-GR-03-1
web_metadata:
  title:
    en: Opening the Door to All Fields of Knowledge:A Presentation on the Aggregates,
      Elements, and Faculties
    bo: ཕུང་ཁམས་བསྐྱེད་མཆེད་ཀྱི་རྣམ་གཞག་ཇི་སྙེད་ཤེས་བྱའི་སྒོ་འབྱེད།
  collection:
    en: IBA Gorampa Series–  Book 3
    bo: གོ་རམས་པ་བསོད་ནམས་སེང་གེ་རྩོམ་བྲིས།–  དེབ། ༣
  author:
    en: Gorampa Sonam Senge
    bo: གོ་རམས་པ་བསོད་ནམས་སེང་གེ
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-GR-03-1
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-GR-03-1.epub
  description:
    en: The widely sought text onskandhas,dhatusandayatanascomposed in 14thcentury
      in Tibet is based on the Abhidharmakosa and widely explores the three themes
      to understand the nature of causes of sufferings.
    bo: གཞུང་འདི་ན་ཀུན་མཁྱེན་ཆེན་པོས་ཁམས་བསྟན་པའི་ལེའུ་ལས། ཟག་བཅས་ཀྱི་ཕུང་པོ་བསྐྱེད་མཆེད་དང་ཁམས་སོགས་སྐོར་རྒྱས་པར་འཆད་ཡོད།
